// Code generated by protoc-gen-go. DO NOT EDIT.
// source: s2s/s2s_msg.proto

package s2s

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqEnter struct {
	MsgId                MSGID    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3,enum=s2s.MSGID" json:"msg_id,omitempty"`
	ServerType           uint32   `protobuf:"varint,2,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	ServerId             uint32   `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqEnter) Reset()         { *m = ReqEnter{} }
func (m *ReqEnter) String() string { return proto.CompactTextString(m) }
func (*ReqEnter) ProtoMessage()    {}
func (*ReqEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8401528ca4415089, []int{0}
}

func (m *ReqEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqEnter.Unmarshal(m, b)
}
func (m *ReqEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqEnter.Marshal(b, m, deterministic)
}
func (m *ReqEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqEnter.Merge(m, src)
}
func (m *ReqEnter) XXX_Size() int {
	return xxx_messageInfo_ReqEnter.Size(m)
}
func (m *ReqEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqEnter.DiscardUnknown(m)
}

var xxx_messageInfo_ReqEnter proto.InternalMessageInfo

func (m *ReqEnter) GetMsgId() MSGID {
	if m != nil {
		return m.MsgId
	}
	return MSGID_S2S_UNSPECIFIED
}

func (m *ReqEnter) GetServerType() uint32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *ReqEnter) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

type RepEnter struct {
	MsgId                MSGID    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3,enum=s2s.MSGID" json:"msg_id,omitempty"`
	ServerType           uint32   `protobuf:"varint,2,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	ServerId             uint32   `protobuf:"varint,3,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RepEnter) Reset()         { *m = RepEnter{} }
func (m *RepEnter) String() string { return proto.CompactTextString(m) }
func (*RepEnter) ProtoMessage()    {}
func (*RepEnter) Descriptor() ([]byte, []int) {
	return fileDescriptor_8401528ca4415089, []int{1}
}

func (m *RepEnter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RepEnter.Unmarshal(m, b)
}
func (m *RepEnter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RepEnter.Marshal(b, m, deterministic)
}
func (m *RepEnter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RepEnter.Merge(m, src)
}
func (m *RepEnter) XXX_Size() int {
	return xxx_messageInfo_RepEnter.Size(m)
}
func (m *RepEnter) XXX_DiscardUnknown() {
	xxx_messageInfo_RepEnter.DiscardUnknown(m)
}

var xxx_messageInfo_RepEnter proto.InternalMessageInfo

func (m *RepEnter) GetMsgId() MSGID {
	if m != nil {
		return m.MsgId
	}
	return MSGID_S2S_UNSPECIFIED
}

func (m *RepEnter) GetServerType() uint32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

func (m *RepEnter) GetServerId() uint32 {
	if m != nil {
		return m.ServerId
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqEnter)(nil), "s2s.ReqEnter")
	proto.RegisterType((*RepEnter)(nil), "s2s.RepEnter")
}

func init() { proto.RegisterFile("s2s/s2s_msg.proto", fileDescriptor_8401528ca4415089) }

var fileDescriptor_8401528ca4415089 = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x36, 0x2a, 0xd6,
	0x2f, 0x36, 0x2a, 0x8e, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2e,
	0x36, 0x2a, 0x96, 0x12, 0x41, 0x12, 0x8f, 0xcf, 0x4c, 0x81, 0x48, 0x29, 0x65, 0x73, 0x71, 0x04,
	0xa5, 0x16, 0xba, 0xe6, 0x95, 0xa4, 0x16, 0x09, 0x29, 0x72, 0xb1, 0x41, 0xe4, 0x24, 0x18, 0x15,
	0x18, 0x35, 0xf8, 0x8c, 0xb8, 0xf4, 0x8a, 0x8d, 0x8a, 0xf5, 0x7c, 0x83, 0xdd, 0x3d, 0x5d, 0x82,
	0x58, 0x73, 0x8b, 0xd3, 0x3d, 0x53, 0x84, 0xe4, 0xb9, 0xb8, 0x8b, 0x53, 0x8b, 0xca, 0x52, 0x8b,
	0xe2, 0x4b, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x83, 0xb8, 0x20, 0x42, 0x21,
	0x95, 0x05, 0xa9, 0x42, 0xd2, 0x5c, 0x9c, 0x50, 0x05, 0x99, 0x29, 0x12, 0xcc, 0x60, 0x69, 0x0e,
	0x88, 0x80, 0x67, 0x0a, 0xc4, 0xb2, 0x02, 0xfa, 0x58, 0x96, 0xc4, 0x06, 0xf6, 0xa0, 0x31, 0x20,
	0x00, 0x00, 0xff, 0xff, 0x70, 0x9e, 0x05, 0x5e, 0x10, 0x01, 0x00, 0x00,
}
