// Code generated by protoc-gen-go. DO NOT EDIT.
// source: c2s/c2s_msg_id.proto

package c2s

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MsgID int32

const (
	MsgID_MSGID_C2S_UNSPECIFIED MsgID = 0
	MsgID_MSGID_C2S_REQ_LOGIN   MsgID = 1
)

var MsgID_name = map[int32]string{
	0: "MSGID_C2S_UNSPECIFIED",
	1: "MSGID_C2S_REQ_LOGIN",
}

var MsgID_value = map[string]int32{
	"MSGID_C2S_UNSPECIFIED": 0,
	"MSGID_C2S_REQ_LOGIN":   1,
}

func (x MsgID) Enum() *MsgID {
	p := new(MsgID)
	*p = x
	return p
}

func (x MsgID) String() string {
	return proto.EnumName(MsgID_name, int32(x))
}

func (x *MsgID) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgID_value, data, "MsgID")
	if err != nil {
		return err
	}
	*x = MsgID(value)
	return nil
}

func (MsgID) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_eeefd9636c64a987, []int{0}
}

func init() {
	proto.RegisterEnum("c2s.MsgID", MsgID_name, MsgID_value)
}

func init() { proto.RegisterFile("c2s/c2s_msg_id.proto", fileDescriptor_eeefd9636c64a987) }

var fileDescriptor_eeefd9636c64a987 = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x49, 0x36, 0x2a, 0xd6,
	0x4f, 0x36, 0x2a, 0x8e, 0xcf, 0x2d, 0x4e, 0x8f, 0xcf, 0x4c, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9,
	0x17, 0x62, 0x4e, 0x36, 0x2a, 0xd6, 0xb2, 0xe6, 0x62, 0xf5, 0x2d, 0x4e, 0xf7, 0x74, 0x11, 0x92,
	0xe4, 0x12, 0xf5, 0x0d, 0x76, 0xf7, 0x74, 0x89, 0x77, 0x36, 0x0a, 0x8e, 0x0f, 0xf5, 0x0b, 0x0e,
	0x70, 0x75, 0xf6, 0x74, 0xf3, 0x74, 0x75, 0x11, 0x60, 0x10, 0x12, 0xe7, 0x12, 0x46, 0x48, 0x05,
	0xb9, 0x06, 0xc6, 0xfb, 0xf8, 0xbb, 0x7b, 0xfa, 0x09, 0x30, 0x02, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x29, 0xb7, 0xb8, 0x5c, 0x58, 0x00, 0x00, 0x00,
}
