// Code generated by protoc-gen-go. DO NOT EDIT.
// source: c2s/c2s_msg.proto

package c2s

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ReqLogin struct {
	MsgId                MSGID    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3,enum=c2s.MSGID" json:"msg_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_3dc542699b482f28, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetMsgId() MSGID {
	if m != nil {
		return m.MsgId
	}
	return MSGID_C2S_UNSPECIFIED
}

func init() {
	proto.RegisterType((*ReqLogin)(nil), "c2s.ReqLogin")
}

func init() { proto.RegisterFile("c2s/c2s_msg.proto", fileDescriptor_3dc542699b482f28) }

var fileDescriptor_3dc542699b482f28 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x36, 0x2a, 0xd6,
	0x4f, 0x36, 0x2a, 0x8e, 0xcf, 0x2d, 0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e,
	0x36, 0x2a, 0x96, 0x12, 0x41, 0x12, 0x8f, 0xcf, 0x4c, 0x81, 0x48, 0x29, 0xe9, 0x72, 0x71, 0x04,
	0xa5, 0x16, 0xfa, 0xe4, 0xa7, 0x67, 0xe6, 0x09, 0x29, 0x72, 0xb1, 0x41, 0xe4, 0x24, 0x18, 0x15,
	0x18, 0x35, 0xf8, 0x8c, 0xb8, 0xf4, 0x92, 0x8d, 0x8a, 0xf5, 0x7c, 0x83, 0xdd, 0x3d, 0x5d, 0x82,
	0x58, 0x73, 0x8b, 0xd3, 0x3d, 0x53, 0x92, 0xd8, 0xc0, 0xba, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x96, 0x06, 0x8c, 0xc3, 0x65, 0x00, 0x00, 0x00,
}
