// Code generated by protoc-gen-go. DO NOT EDIT.
// source: c2s/test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneType int32

const (
	PhoneType_HOME PhoneType = 0
	PhoneType_WORK PhoneType = 1
)

var PhoneType_name = map[int32]string{
	0: "HOME",
	1: "WORK",
}

var PhoneType_value = map[string]int32{
	"HOME": 0,
	"WORK": 1,
}

func (x PhoneType) String() string {
	return proto.EnumName(PhoneType_name, int32(x))
}

func (PhoneType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_185040f6da940ceb, []int{0}
}

//手机
type Phone struct {
	MsgId                uint32    `protobuf:"varint,1,opt,name=msg_id,json=msgId,proto3" json:"msg_id,omitempty"`
	Type                 PhoneType `protobuf:"varint,2,opt,name=type,proto3,enum=test.PhoneType" json:"type,omitempty"`
	Number               int32     `protobuf:"varint,3,opt,name=number,proto3" json:"number,omitempty"`
	Name                 string    `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Phone) Reset()         { *m = Phone{} }
func (m *Phone) String() string { return proto.CompactTextString(m) }
func (*Phone) ProtoMessage()    {}
func (*Phone) Descriptor() ([]byte, []int) {
	return fileDescriptor_185040f6da940ceb, []int{0}
}

func (m *Phone) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Phone.Unmarshal(m, b)
}
func (m *Phone) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Phone.Marshal(b, m, deterministic)
}
func (m *Phone) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Phone.Merge(m, src)
}
func (m *Phone) XXX_Size() int {
	return xxx_messageInfo_Phone.Size(m)
}
func (m *Phone) XXX_DiscardUnknown() {
	xxx_messageInfo_Phone.DiscardUnknown(m)
}

var xxx_messageInfo_Phone proto.InternalMessageInfo

func (m *Phone) GetMsgId() uint32 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

func (m *Phone) GetType() PhoneType {
	if m != nil {
		return m.Type
	}
	return PhoneType_HOME
}

func (m *Phone) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Phone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("test.PhoneType", PhoneType_name, PhoneType_value)
	proto.RegisterType((*Phone)(nil), "test.Phone")
}

func init() { proto.RegisterFile("c2s/test.proto", fileDescriptor_185040f6da940ceb) }

var fileDescriptor_185040f6da940ceb = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x36, 0x2a, 0xd6,
	0x2f, 0x49, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0x95, 0xf2,
	0xb9, 0x58, 0x03, 0x32, 0xf2, 0xf3, 0x52, 0x85, 0x44, 0xb9, 0xd8, 0x72, 0x8b, 0xd3, 0xe3, 0x33,
	0x53, 0x24, 0x18, 0x15, 0x18, 0x35, 0x78, 0x83, 0x58, 0x73, 0x8b, 0xd3, 0x3d, 0x53, 0x84, 0x94,
	0xb9, 0x58, 0x4a, 0x2a, 0x0b, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0xf8, 0x8c, 0xf8, 0xf5, 0xc0,
	0x06, 0x80, 0x75, 0x84, 0x54, 0x16, 0xa4, 0x06, 0x81, 0x25, 0x85, 0xc4, 0xb8, 0xd8, 0xf2, 0x4a,
	0x73, 0x93, 0x52, 0x8b, 0x24, 0x98, 0x15, 0x18, 0x35, 0x58, 0x83, 0xa0, 0x3c, 0x21, 0x21, 0x2e,
	0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x16, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x5b, 0x4b, 0x9e,
	0x8b, 0x13, 0xae, 0x5d, 0x88, 0x83, 0x8b, 0xc5, 0xc3, 0xdf, 0xd7, 0x55, 0x80, 0x01, 0xc4, 0x0a,
	0xf7, 0x0f, 0xf2, 0x16, 0x60, 0x4c, 0x62, 0x03, 0x3b, 0xcf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x95, 0x8d, 0x88, 0x42, 0xb0, 0x00, 0x00, 0x00,
}
